# Generated by Django 4.2.1 on 2023-05-10 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Optotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='optotypes/')),
            ],
        ),
        migrations.CreateModel(
            name='MotionVisionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optotype_order', models.CharField(help_text='Comma separated list of optotype IDs in order', max_length=20)),
                ('rotation_speed', models.IntegerField(help_text='Speed of the rotating optotypes (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('correct_direction', models.CharField(help_text='Direction of rotation (e.g. "clockwise")', max_length=50)),
                ('optotypes', models.ManyToManyField(to='motion_vision.optotype')),
            ],
        ),
    ]
