# Generated by Django 4.2.1 on 2023-05-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optotype',
            options={'ordering': ['optotype_id']},
        ),
        migrations.RemoveField(
            model_name='optotype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='optotype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='optotype',
            name='name',
        ),
        migrations.AddField(
            model_name='optotype',
            name='optotype_char',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optotype',
            name='optotype_id',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optotype',
            name='optotype_image',
            field=models.ImageField(blank=True, null=True, upload_to='optotypes/'),
        ),
    ]
