# Generated by Django 4.2.1 on 2023-05-10 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVisionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rg_score', models.IntegerField(blank=True, null=True)),
                ('rg_result', models.CharField(blank=True, max_length=50, null=True)),
                ('rg_chart', models.ImageField(blank=True, null=True, upload_to='color_vision/charts')),
                ('by_score', models.IntegerField(blank=True, null=True)),
                ('by_result', models.CharField(blank=True, max_length=50, null=True)),
                ('by_chart', models.ImageField(blank=True, null=True, upload_to='color_vision/charts')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
