# Generated by Django 4.2.1 on 2023-05-10 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('line', 'Line optotype'), ('number', 'Number optotype'), ('color', 'Color vision test')], max_length=50)),
                ('result', models.FloatField()),
                ('notation', models.CharField(blank=True, max_length=10, null=True)),
                ('is_astigmatic', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual_acuity.exam')),
            ],
        ),
        migrations.CreateModel(
            name='OptokineticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveSmallIntegerField()),
                ('direction', models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical')], max_length=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual_acuity.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ETDRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveSmallIntegerField()),
                ('columns', models.PositiveSmallIntegerField()),
                ('chart', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual_acuity.exam')),
            ],
        ),
    ]
